In [1]:
# सबसे पहले लाइब्रेरी इम्पोर्ट करें
from sklearn.model_selection import train_test_split
import numpy as np

# मान लेते हैं हमारे पास 10 स्टूडेंट्स के 'पढ़ाई के घंटे' (X) और उनके 'मार्क्स' (y) हैं
X = np.array([[2], [3], [4], [5], [6], [7], [8], [9], [10], [11]]) # Features
y = np.array([40, 45, 50, 60, 65, 70, 80, 85, 90, 95])            # Target (Labels)

# डेटा को Train (80%) और Test (20%) में बांटना
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("पढ़ाई के लिए डेटा (X_train):\n", X_train)
print("एग्जाम के लिए डेटा (X_test):\n", X_test)


पढ़ाई के लिए डेटा (X_train):
 [[ 7]
 [ 2]
 [ 9]
 [ 4]
 [11]
 [ 6]
 [ 5]
 [ 8]]
एग्जाम के लिए डेटा (X_test):
 [[10]
 [ 3]]


In [2]:
from sklearn.model_selection import train_test_split
import numpy as np

# X = पढ़ाई के घंटे, y = परीक्षा में आए मार्क्स
X = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]) 
y = np.array([35, 40, 45, 50, 55, 65, 75, 80, 85, 95])

# डेटा को Train (80%) और Test (20%) में बांटना
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("--- ट्रेनिंग का डेटा (मॉडल इससे सीखेगा) ---")
print("पढ़ाई के घंटे:\n", X_train)
print("आए हुए मार्क्स:\n", y_train)

print("\n--- टेस्टिंग का डेटा (इससे मॉडल का एग्जाम होगा) ---")
print("एग्जाम के लिए घंटे:\n", X_test)


--- ट्रेनिंग का डेटा (मॉडल इससे सीखेगा) ---
पढ़ाई के घंटे:
 [[ 6]
 [ 1]
 [ 8]
 [ 3]
 [10]
 [ 5]
 [ 4]
 [ 7]]
आए हुए मार्क्स:
 [65 35 80 45 95 55 50 75]

--- टेस्टिंग का डेटा (इससे मॉडल का एग्जाम होगा) ---
एग्जाम के लिए घंटे:
 [[9]
 [2]]
