In [ ]:
## Functions()


In [1]:
# function ---> resuable block of code
# def ---> keyword --->  defining function
# designed to perform a specified task
# syntax: 

# def function_name():
#     block of code

# function 
# 1) predefined --> len(),id(),type()
# 2) userdefined ----> 1)parameterized  2) non-parameterized
        #syntax --->   # def function_name(a,b):  # def function_name():
                        #     block of code        #     block of code

#1)parameterized ----> if we are passing anythings in functions name parathensis then it is called parameterized

#2) non-parameterized --> if we are not passing anythings in functions name parathensis then it is called parameterized




In [2]:
#2) non-parameterized

def vishnu():
    print("A")
    print("B")
    print("C")
vishnu()

A
B
C


In [ ]:
# sub , mul, division

In [4]:
#1)parameterized

def mango(fruit):
    print("i like ",fruit)
mango("mango")


i like  mango


In [1]:
## Addition 


In [20]:
def add(a, b): 
  return a + b  # This line sends back sum of a and b 
result = add(3,5)
print(result)      
# Output: 8 

8


In [22]:
def sub(a, b): 
  return a - b  # This line sends back sum of a and b 
result = sub (34,5)
print(result)      
# Output: 8 

29


In [24]:
def mul(a, b): 
  return a * b  # This line sends back sum of a and b 
result = mul (7,5)
print(result)      
# Output: 8 

35


In [16]:
def divide(a, b):   # a,b are 2 parameters 
 return a / b 
result = divide(b=10, a=20) # with keyword arguments 
print(result)    
# Output: 2 

2.0


## Argument 

In [ ]:
# Explanation for default argument: 
# -- Default arguments are values that are provided while defining functions.
# -- The assignment operator = is used to assign a default value to the argument.
# -- Default arguments become optional during the function calls.
# -- If we provide a value to the default arguments during function calls, it overrides the default value.
# -- The function can have any number of default arguments.
# -- Default arguments should follow non-default arguments.


#1.positional
#2.keyword
#3.default
#4.Arbitary

In [ ]:
# ## Positional Argument

In [1]:
# argument passed in order called as positional arguement

def val(name,surname):
    print(f'my name is {name}) and my surname is {surname}')
val("vishnu","chacherkar")

my name is vishnu) and my surname is chacherkar


In [9]:
# Keyword Argument

def val(name,surname):
    print(f'my name is {name} and my surname is {surname}')
val( surname ="chacherkar", name= "vishnu" )


my name is vishnu and my surname is chacherkar


In [14]:
# Default Argument

def pli(a,b=10):
    print(a+b)
pli(10)

20


In [2]:
def pli(a,b=2):
    print(a+b)
pli(10)

12


In [16]:
def pli(a,b,c=10):
    print(a+b)
pli(10,20)

30


In [6]:
def pli(a,b=20):
    print(a+b)
pli(10)

30


In [ ]:
### Arbitary Arguments

In [ ]:
#Arbitary Arguments(*args and **kwargs)


In [6]:
def add(*v):
    print((v))
add(10,20,30,40)

(10, 20, 30, 40)


In [1]:
def ab(*argv):
    print(sum(argv))          
ab(10,20,30,40)

100


In [2]:
# lambda function 
# anonymous function defined usoing lambda 

l= lambda n: n*n
print(l(2))

4


In [3]:
p= lambda n,m: n*m
print(p(2,3))

6


In [7]:

# Take 2 parameters, add them, then divide by 2
p = lambda n, m: (n + m) / 2

print(p(2, 3))

2.5


In [8]:
def msg():
    print("hello")
    return "world"

r=msg()
print(r)

hello
world


In [19]:
## Factorial
def fac(f):
    if f<=1:
        return 1
    return f*fac(f-1)
fac(5)

120

In [3]:
# reverse a string using inxing,if ,return 


v='hello'
print(v[::-1])


olleh


In [26]:
### reverse a string using inxing,if ,return 

def rev(name):
    if len(name)==0:
        return name
    return name[-1]+rev(name[:-1])
rev("vishnu")



'unhsiv'

In [16]:
def reverse(a):    
        return a[::-1]   
reverse("vishnu")

'unhsiv'

In [43]:
def av(a):
    if a==1:
      return 1
    return a+ av(a-1)
av(10)
     

55

In [45]:
def av(a):
    if a == 1:
        return 1
    return a + av(a - 1)


print(av(5))  

15


In [5]:
## positonal only arguement 

def add(a,b,/):
    print(a+b)
add(10,20)

30


In [7]:
## keyword only arguement 

def add(*,a,b):
    print(a+b)
add(a=10,b=20)

30


In [12]:
## positonal only & keyword only arguement 

def add(a,b,/,*,c,d):
    print(a+b+c+d)
add(10,20,c=30,d=40)



100


## Functions Scope(local & global variable)

In [18]:
# LOCAL SCOPE ----> variable inside a function

def sco():
    a=10
    print("value of a : ",a)
sco()

value of a :  10


In [20]:
# GLOBAL SCOPE -----> variable outside any function

def sco():
    a=10
    print("value of a : ",a)
sco()
a=20
print("value of a : ",a)

value of a :  10
value of a :  20


In [21]:
a=20
def sco():
    a=10
    print("value of a : ",a)
    print("value of a : ",a)
sco()

print("value of a : ",a)

value of a :  10
value of a :  10
value of a :  20


In [27]:
## nested function 

b=20
def outer():
    a=10
    print("this is outer function")
    print(a)
    def inner():
        print("this is a inner function" )
        print(a)
        print(a)
        print(b)
    inner()
outer()
print("value of b" ,b)  

this is outer function
10
this is a inner function
10
10
20
value of b 20


In [11]:
# global variable


def outer():
    global a 
    a=10
    print(a)
   
outer()
print("value of",a)


10
value of 10


In [12]:
## Higher Order Function
## function that take another function an argument

def cal(a,b):
    return a(b)
def squ(x):
    return x*x
cal(squ,4)


16

In [31]:
def calculator(x,y,z):
    return x(y,z)
def add(a,b):
    return a+b
    
def mul(a,b):
    return a*b
mul(10,20)

def sub(a,b):
    return a-b
sub(10,20)

def div(a,b):
    return a/b
div(10,20)


calculator(add,10,20)  
calculator(mul,10,20) 


200

In [33]:
def alphabet():
    for i in range(65, 91):
        print(chr(i), end=" ")

alphabet()

A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 

In [1]:


l=(1,2,3)
l2=(1,2,3,4,5,6)

comp(l,l2)

NameError: name 'comp' is not defined

In [1]:
balance=10000


while True:

    print("""
    1.Check Balance
    2.Deposit
    3.Withdraw
    4.Exit
    """)


    choice=int(input("Choose option: "))


    if choice==1:

        print(balance)


    elif choice==2:

        amount=int(input("Deposit amount: "))

        balance+=amount


    elif choice==3:

        amount=int(input("Withdraw amount: "))


        if amount<=balance:

            balance-=amount

        else:

            print("Insufficient Balance")


    elif choice==4:

        break


    else:

        print("Invalid Choice")


    1.Check Balance
    2.Deposit
    3.Withdraw
    4.Exit
    


Choose option:  1


10000

    1.Check Balance
    2.Deposit
    3.Withdraw
    4.Exit
    


Choose option:  2
Deposit amount:  150000



    1.Check Balance
    2.Deposit
    3.Withdraw
    4.Exit
    


Choose option:  1


160000

    1.Check Balance
    2.Deposit
    3.Withdraw
    4.Exit
    


Choose option:  3
Withdraw amount:  400



    1.Check Balance
    2.Deposit
    3.Withdraw
    4.Exit
    


Choose option:  1


159600

    1.Check Balance
    2.Deposit
    3.Withdraw
    4.Exit
    


Choose option:  4


In [1]:
def greet(name="Guest"):
    print("Hello", name)

greet()          # Hello Guest
greet("Apurva")  # Hello Apurva

Hello Guest
Hello Apurva


In [7]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

print("Array =", arr1)
print("Type =", type(arr1))
print("Dimension =", arr1.ndim)
print("Shape =", arr1.shape)
print("Size =", arr1.size)

Array = [10 20 30 40 50]
Type = <class 'numpy.ndarray'>
Dimension = 1
Shape = (5,)
Size = 5


In [13]:
import numpy as np

arr3 = np.array([
    [[1, 2, 3],[4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print("Array =")
print(arr3)

print("Type =", type(arr3))
print("Dimension =", arr3.ndim)
print("Shape =", arr3.shape)
print("Size =", arr3.size)

Array =
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Type = <class 'numpy.ndarray'>
Dimension = 3
Shape = (2, 2, 3)
Size = 12


In [15]:
# For Lists
items = ['a', 'b', 'c']
print(list(reversed(items)))  
# Output: ['c', 'b', 'a']

# For Strings
text = "Python"
print(" ".join(reversed(text)))
# Output: nohtyP


['c', 'b', 'a']
n o h t y P
