In [37]:
import numpy as np

In [38]:
a= np.arange(10)
print(a)
print(a.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [39]:
import numpy as np

r = np.array([1, 2, 3, 4, 5, 6, 7, 8])
v = r.reshape(2, 4)
print(v)


[[1 2 3 4]
 [5 6 7 8]]


In [40]:
# 1. Shape of the array
print(v.shape)

# 2. Number of dimensions
print( v.ndim)

# 3. Element size in bytes
print("3. Itemsize (bytes per element):", v)



(2, 4)
2
3. Itemsize (bytes per element): [[1 2 3 4]
 [5 6 7 8]]


In [41]:
# 4. Boolean array and its dtype

f = np.full((3, 4), True)
print(f)
print(f.dtype)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
bool


In [42]:
f = np.ones((2, 3), dtype=bool)
print(f)

[[ True  True  True]
 [ True  True  True]]


In [43]:
#6 Create a 3x4 matrix filled with only zeros
z= np.ones([3,4])
print(z)
print(z.ndim)
print(type(z))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2
<class 'numpy.ndarray'>


In [44]:
z= np.zeros([3,4])
print(z)
print(z.ndim)
print(type(z))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
<class 'numpy.ndarray'>


In [45]:
#7 create a numpy array using linspace function
l = np.linspace(1,10,6)
l


array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [46]:
#8 convert a pythonlist into numpy array
import numpy as np
py_list = [10, 20, 30, 40]
arr8 = np.array(py_list)
print(arr8)


[10 20 30 40]


In [47]:
# Exercise 9: Find the memory size of a NumPy array of numbers from 0 to 9
arr9 = np.arange(10)
memory_size = arr9.size * arr9.itemsize
print( memory_size)

80


In [48]:
# Exercise 10: Reverse a 1D NumPy array
arr10 = arr9[::-1]
print(arr10)

[9 8 7 6 5 4 3 2 1 0]


In [49]:
# Exercise 11: Create a 3x3 identity matrix
arr11 = np.eye(3)
print(arr11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
# Exercise 12: Create a 4x4 array and extract its first row and last column
arr12 = np.arange(16).reshape(4, 4)
first_row = arr12[0, :]
last_col = arr12[:, -1]
print(arr12)
print()
print(first_row)
print(last_col)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[0 1 2 3]
[ 3  7 11 15]


In [51]:
# Exercise 13: Extract Odd Rows and Even Columns
import numpy as np

arr = np.arange(16).reshape(4, 4)
result = arr[1::2, ::2]

print(arr)
print()
print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 4  6]
 [12 14]]


In [52]:
# Exercise 14: Stack arrays horizontally
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

result = np.hstack((a1, a2))
print(result)

[1 2 3 4 5 6]


In [53]:
# Exercise 15: Slice the first two rows and first two columns from a 4x4 array
import numpy as np

arr = np.arange(16).reshape(4, 4)
result = arr[:2, :2]

print(arr)

print()
print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0 1]
 [4 5]]


In [54]:
# Exercise 16: Replace all odd numbers in a NumPy array with -1
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[arr % 2 != 0] = -1

print(arr)

[-1  2 -1  4 -1  6 -1]


In [55]:
# Exercise 17: Get the indices of non-zero elements in an array
import numpy as np

arr = np.array([1, 0, 2, 0, 3, 4])
indices = np.nonzero(arr)

print(indices[0])

[0 2 4 5]


In [56]:
# Exercise 18: Find the common items between two arrays
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

common = np.intersect1d(a, b)
print(common)

[3 4 5]


In [57]:
# Exercise 19: Perform arithmetic operations on two NumPy arrays element-wise
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print(a + b)
print()
print(a - b)
print()
print(a * b)
print()
print(a / b)

[12 24 35]

[ 8 16 25]

[ 20  80 150]

[5. 5. 6.]


In [58]:
# Exercise 20: Matrix multiplication
import numpy as np

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

result = np.matmul(m1,m2)  
print(result)

[[19 22]
 [43 50]]


In [59]:
# Exercise 21: Compute the mean, median, and standard deviation of a NumPy array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

30.0
30.0
14.142135623730951


In [60]:
# Exercise 22: Remove common items from array
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

result = np.setdiff1d(a, b)
print( result)


[1 2]


In [61]:
# Exercise 23: Normalize a NumPy array (values between 0 and 1)
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [62]:
# Exercise 24: Get the positions where elements of array a and b match
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 3, 2, 5])

positions = np.where(a == b)
print( positions)


(array([0, 2, 4]),)


In [63]:
# Exercise 25: Extract numbers from an array (between 5 and 10)
import numpy as np

arr = np.array([2, 6, 1, 9, 10, 3, 27, 8])
extracted = arr[(arr >= 5) & (arr <= 10)]

print(extracted)

[ 6  9 10  8]


In [64]:
# Exercise 26: Create a random 3x2 matrix and find its maximum and minimum values
import numpy as np

rand_matrix = np.random.rand(3, 2)

print(rand_matrix)
print()
print(rand_matrix.max())
print(rand_matrix.min())

[[0.9842846  0.88027103]
 [0.69389051 0.07769758]
 [0.03617705 0.48237977]]

0.9842845953279774
0.036177050049844284


In [65]:
# Exercise 27: Sorting a NumPy array based on a specific column
import numpy as np

arr = np.array([[1, 4, 9], [3, 1, 6], [5, 2, 8]])

# Sort based on 2nd column (index 1)
sorted_arr = arr[arr[:, 1].argsort()]
print(arr)
print()
print( sorted_arr)

[[1 4 9]
 [3 1 6]
 [5 2 8]]

[[3 1 6]
 [5 2 8]
 [1 4 9]]


In [66]:
# Exercise 30: Generate 10 random integers between 1 and 100
import numpy as np

rand_ints = np.random.randint(1, 101, size=10)

print(rand_ints)

[51 23 36 19 65 61 69 17 31  1]


In [67]:
# Exercise 31: Create a 3x3 array of random integers and sort it row wise
import numpy as np

arr = np.random.randint(1, 100, size=(3, 3))
print(arr)
print()
sorted_row = np.sort(arr, axis=1)
print(sorted_row)

[[ 3 84 14]
 [ 4 16 76]
 [69 92 34]]

[[ 3 14 84]
 [ 4 16 76]
 [34 69 92]]


In [68]:
# Exercise 32: Shuffle an array randomly
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
np.random.shuffle(arr)

print(arr)

[10 40 20 30 50]


In [69]:
# Exercise 33: Create a 5x5 2D array with 1s on the border and 0s inside
import numpy as np

arr = np.ones((5, 5), dtype=int)
arr[1:-1,1:-1]=0

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [70]:
# Exercise 37: Stack two arrays vertically and horizontally
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))
print()
print(np.hstack((a, b)))


[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [71]:
# Exercise 38: Split an array into 3 equal parts
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
parts = np.split(arr, 3)
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [72]:
# Exercise 39: Perform Addition and Squaring on Arrays


In [81]:
import numpy as np 
np.random.rand(1,25)



array([[0.20416951, 0.6826908 , 0.36882029, 0.66997067, 0.51700109,
        0.44760834, 0.22513503, 0.81070751, 0.51368181, 0.12283742,
        0.7192952 , 0.0607308 , 0.64976586, 0.15479553, 0.12218407,
        0.5233422 , 0.72475733, 0.32210946, 0.93530625, 0.70904672,
        0.0634939 , 0.75857992, 0.53096342, 0.0064062 , 0.79893361]])

In [86]:
arr = np.arange(26)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [99]:
import numpy as np

# Generates 25 numbers (0 to 24) and shapes them into a 5x5 grid
arr = np.arange(25).reshape(5, 5)
print(arr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [100]:
arr = np.arange(12).reshape(3, 4)
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [126]:
a = np.arange(20)
a.dtype


dtype('int64')

In [124]:
result= a[a>13]
result

array([14, 15, 16, 17, 18, 19])

In [ ]:
np.mean(a)

np.float64(9.5)

In [113]:
np.max(a)

np.int64(19)

In [125]:
np.abs(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [114]:
np.min(a)

np.int64(0)

In [115]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

result = np.matmul(m1,m2)  
print(result)

[[19 22]
 [43 50]]
